on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: pguyot/arm-runner-action@v2
      with:
        commands: |
            apt-get install -y --no-install-recommends git tree
            git submodule update --init src/build
            cd src/build
            tree
            
