on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: pguyot/arm-runner-action@v2  
      with:
        image_additional_mb: 10000
        commands: |
            apt-get install -y --no-install-recommends \
              build-essential curl ca-certificates sudo git lintian \
              pkg-config libudev-dev libssl-dev libapt-pkg-dev libclang-dev \
              libpam0g-dev raspberrypi-kernel-headers uuid-dev git
            git submodule update --init src/build
            cd src/build
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -sSf | sh -s -- -y
            . ~/.cargo/env
            ./build.sh
            mv packages/*.deb ../../main
    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        author_name: Dexogen
        author_email: dexogen@gmail.com
        message: 'fresh build'
        add: '*'  
